export { default as Header } from './Header/Header'
export { default as ImageWithPlot } from './ImageWithPlotProps/ImageWithPlotProps'
export { default as InfoButtons } from './InfoButtons/InfoButtons'
export { default as MovieInfo } from './MovieInfo/MovieInfo'
export { default as Posters } from './Posters/Posters'
export { default as BoxOffice } from './PostOffice/PostOffice'
